### ISSUE TITLE
Test and Instructions conflict

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/ruby-collaborating-objects-lab#36]
Within song_spec.rb, the test calls one instance method that we have to make "artist=" and the instructions require it to be called "artist_name=" in order to pass.  This discrepancy, with it being a test based lab, caused a lot of confusion and extra time.

Additionally, the expectations/functionality written in mp3_importer_spec 'imports the files into the library by creating songs from a filename' are not exactly clear as to what needs to be done.  I never would have guessed from the half sentence given that I needed an iterator.  I was only able to figure this out by looking at the github solution.  I would suggest being more clear by saying something like 'imports all files into the library by creating each file into a song from a filename'.

**Comment by maxwellbenton** [comment]
Hi @regilfillan,

Thank you for spotting this and providing feedback. We updated this lab's tests and instructions so that it is clear that there is both an `artist=` accessor required, as well as an `artist_name=` method, and corrected the references. We've also updated the tests for these methods to ensure future students know to set both up.

We apologize for any inconvenience this issue may have caused. Thank you for contributing to a Learn lesson!
